version: "3.8"

networks:
  todo-net:

volumes:
  mysql-data:

services:
  mysql:
    image: mysql:8.0
    container_name: todo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - todo-net
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: andrews326/todo-backend:latest
    container_name: todo-backend
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - todo-net
    ports:
      - "9000:9000"

  ui:
    image: andrews326/todo-frontend:latest
    container_name: todo-frontend
    depends_on:
      - app
    networks:
      - todo-net
    ports:
      - "3000:80"
